namespace EbookReader.Config.CommandGrid
{
    public enum GridCommand 
    {
        None,
        PrevPage,
        NextPage,
        PrevChapter,
        NextChapter,
        VisualizeCommandCells,
        OpenQuickSettings,
        ToggleFullscreen,
        Quit,
        CloseBook,
        BookInfo,
        Mark,
        ToggleMarking,
        Sync,
        Backup,
        NextTheme,
        PrevTheme,
        SetTheme,
        Goto,
        Search,
        FontSizePlus,
        FontSizeMinus,
        BrightnessPlus,
        BrightnessMinus,
        Restore
    }
}